### ISSUE TITLE
Vertical metrics do not match GF version

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/Catamaran-Tamil#6]
![Desktop_Windows_10_chrome_69 0_](https://user-images.githubusercontent.com/7525512/83271794-3ac5f280-a1c2-11ea-9a90-638b8d0dc43b.gif)

If the original metrics are not consistent, please ensure that the family's metrics are the same the previous Regular.

**Comment by pichotta** [comment]
@moyogo   please see above comment re: vertical metrics fix.

**Comment by moyogo** [comment]
The original metrics were not consistent Black had ascent=1100, descent=-500 (hhea and win), but Regular and Light had ascent=1100, descent=-540. The new fonts all use the second set of values (hhea, typo and win).
