### ISSUE TITLE
Outlines: Oslash and oslash

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Catamaran-Tamil#7]
@djrrb 

In Catamaran could you look into the /Oslash and /oslash. Their outlines and path direction and the way it renders?  I have tried recomposing, changing path directions and start points. It looks okay in sources but not in TTFs

![Screen Shot 2020-06-19 at 9 31 44 PM](https://user-images.githubusercontent.com/6576107/85328972-a89eca80-b49f-11ea-9bc4-9faf4f9406dd.png)

**Comment by djrrb** [comment]
@pichotta Where are you checking these TTFs? 

They look okay over here.

<img width="1256" alt="Screen Shot 2020-06-23 at 8 23 59 PM" src="https://user-images.githubusercontent.com/6578861/85481286-897f6600-b58f-11ea-8188-8a23f6326bcd.png">


<img width="1701" alt="Screen Shot 2020-06-23 at 8 24 38 PM" src="https://user-images.githubusercontent.com/6578861/85481327-9c923600-b58f-11ea-8cf4-f666b866868d.png">

**Comment by pichotta** [comment]
@djrrb I re-cloned the repo and when I load the TTFs I still see the overlaps in Gauntlet and type tools.typenetwork.com  Not in VF in either.


![Oslash 2020-06-23 at 8 32 56 PM](https://user-images.githubusercontent.com/6576107/85482241-07903c80-b591-11ea-8371-47a3085eceb7.png)

![Oslash typeools tn 2020-06-23 at 8 36 16 PM](https://user-images.githubusercontent.com/6576107/85482662-58a03080-b591-11ea-9324-c85e5bb05215.png)

**Comment by djrrb** [comment]
Ah, the static fontmake command had a `keep-overlaps` argument. I’ve removed it and rebuild. Hopefully that addresses the issue: https://github.com/TypeNetwork/Catamaran-Tamil/pull/8
