### ISSUE TITLE
Color of tm_Aa appears too light

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/Catamaran-Tamil#9]
Everything looks good apart from this one particular glyph.

In body text sizes, the right hand part of the glyph looks too light

<img width="215" alt="Screenshot 2020-07-07 at 14 59 12" src="https://user-images.githubusercontent.com/7525512/86792571-8b9ef580-c062-11ea-949e-1e90b1a39da6.png">

![cata1_s](https://user-images.githubusercontent.com/7525512/86792594-8f327c80-c062-11ea-8272-b9c0b80a9ffe.gif)

I don't know what is causing this issue. The outlines seem ok when I inspect the sources in a font editor.

This is happening on Mac Chrome Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by moyogo** [comment]
I can reproduce in Mac Chrome, there’s also an issue with where the two contours should meet at some sizes:
<img width="67" alt="image" src="https://user-images.githubusercontent.com/1923747/87165750-7a542400-c2c2-11ea-84ad-22f482b55ae5.png">

I’m getting some similar artifacts with tm_Aa ஆ when I turn on the autohinting with ftview. I don’t think Mac Chrome uses autohinting though.
I’ll see if correcting one of the two countour direction, adding overlap between the two contours or removing the overlap helps.

**Comment by moyogo** [comment]
Correcting one of the two contour direction, adding overlap between the two contours seems to fix it:
<img width="64" alt="image" src="https://user-images.githubusercontent.com/1923747/87166959-33672e00-c2c4-11ea-930e-74b18705df5a.png">

Here’s the VF:
[Catamaran[wght].ttf.zip](https://github.com/TypeNetwork/Catamaran-Tamil/files/4903732/Catamaran.wght.ttf.zip)

Are there other glyphs with the same issue?
I’ll see if there are similar glyphs (with two contours almost overlapping, with different contour directions).

**Comment by moyogo** [comment]
OK it happens with other glyphs as well like tm_eight ௮. The issue seems to be different contour directions. It’s not the outlines touching without overlap, tm_A has this but doesn’t have this issue.
